### ISSUE TITLE
хмм

### ISSUE THREAD

**Issue by OzoneReloaded** [rustam1998/pendulum-simulator#1]
кажется вы лох

**Comment by OzoneReloaded** [comment]
это конечно не точно но вроде лох

**Comment by rustam1998** [comment]
Здравствуйте, Глеб! Я проверил сказанное вами путем смотрения в зеркало. Действительно, оказалось, что я лох в какой-то мере. Я серьезно возьмусь за это дело и, надеюсь, исправить данную ошибку.

**Comment by rustam1998** [comment]
> это конечно не точно но вроде лох

Здравствуйте, Глеб! Я проверил сказанное вами путем смотрения в зеркало. Действительно, оказалось, что я лох в какой-то мере. Я серьезно возьмусь за это дело и, надеюсь, исправить данную ошибку.
